language: python

python:
        - "3.5.3"

install:
        - pip install -r requirements.txt
        - pip install pyinstaller
        - pyinstaller OpenMineMods.spec

before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3


deploy:
        provider: script
        script: .travis/deploy.sh
